version: '3'
services:
  npm_proxy:
    container_name: 'npm_proxy'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/admin/docker-data/npm_proxy:/data
networks:
  default:
    external:
      name: npm_proxy