---
version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.26.0
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/admin/docker-data/bitwarden:/data
networks:
  default:
    external:
      name: npm_proxy