version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/admin/docker/heimdall/data:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - rev-proxy
networks:
  rev-proxy:
    external: true