---
version: '3.3'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.8
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/jellyfin/config:/config
      - /var/docker/jellyfin/cache:/cache
      - /home/admin/docker-data/jellyfin:/data
networks:
  default:
    external:
      name: npm_proxy