---
version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.18.5
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/admin/docker/uptime-kuma/data/config:/app/data
    security_opt:
      - no-new-privileges:true
    networks:
      - rev-proxy
networks:
  rev-proxy:
    external: true