version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /home/admin/hdd/:/data
      - /home/admin/docker/filebrowser/data/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${domain}`)"
      - "traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect"
      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.rule=Host(`files.${domain}`)"
      - "traefik.http.routers.filebrowser-secure.tls=true"
      - "traefik.http.routers.filebrowser-secure.service=filebrowser"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=8080"
      - "traefik.docker.network=rev-proxy"  
    security_opt:
      - no-new-privileges:true
    networks:
      - rev-proxy
networks:
  rev-proxy:
    external: true