---
version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.18.5
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/docker-data/uptime-kuma/config:/app/data
networks:
  default:
    external:
      name: npm_proxy