version: '3.3'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.8
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/admin/docker/jellyfin/data/config:/config
      - /home/admin/docker/jellyfin/data/cache:/cache
      - /home/admin/hdd/jellyfin:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${domain}`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${domain}`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=80"
      - "traefik.docker.network=rev-proxy"
    security_opt:
      - no-new-privileges:true
    networks:
      - rev-proxy
networks:
  rev-proxy:
    external: true