version: '3'
services:
  db:
    image: mariadb:10.5
    container_name: 'nextcloud_db'
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/admin/hdd/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - default

  app:
    image: nextcloud
    container_name: 'nextcloud_app'
    restart: always
    links:
      - db
    volumes:
      - /home/admin/hdd/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
networks:
  default:
    external:
      name: npm_proxy